baseURL = 'https://strikeforroe.github.io/'
languageCode = 'en-us'
title = 'StrikeForRoe'
theme = "hugo-theme-codex"

[params]
reddit = "https://www.reddit.com/r/StrikeForRoe/"
twitter = "https://twitter.com/search?q=%23StrikeForRoe&src=trend_click&vertical=trends"

iconOrder = ["reddit","twitter"]


[[menu.main]]
  identifier = "about"
  name = "#StrikeForRoe"
  title = "Strike For Roe!"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "When?"
  title = "Blog"
  url = "/blog"